-- ================================================================
-- Image Frame Generator — Complete MySQL Database Schema
-- PHP 8.2 + MySQL 8.0 | Character Set: utf8mb4
-- ================================================================

CREATE DATABASE IF NOT EXISTS `image_frame_generator`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE `image_frame_generator`;

-- ================================================================
-- 1. ADMINS TABLE
-- Stores admin credentials for the backend dashboard
-- ================================================================
CREATE TABLE IF NOT EXISTS `admins` (
    `id`         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `username`   VARCHAR(50) NOT NULL UNIQUE,
    `email`      VARCHAR(150) DEFAULT NULL,
    `password`   VARCHAR(255) NOT NULL,
    `role`       ENUM('super_admin', 'admin', 'editor') NOT NULL DEFAULT 'admin',
    `last_login` DATETIME DEFAULT NULL,
    `is_active`  TINYINT(1) NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Default admin: username 'admin', password 'admin123'
INSERT INTO `admins` (`username`, `email`, `password`, `role`)
VALUES ('admin', 'admin@example.com', '$2y$12$moOuM2CIDa.ezlm5DZQT7un05qDXN1eo/UQUdp9oPOJbt2Wh9uuXG', 'super_admin')
ON DUPLICATE KEY UPDATE `password` = VALUES(`password`);

-- ================================================================
-- 2. USERS TABLE
-- Tracks anonymous/guest users who generate images
-- ================================================================
CREATE TABLE IF NOT EXISTS `users` (
    `id`         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name`       VARCHAR(100) DEFAULT NULL,
    `email`      VARCHAR(150) DEFAULT NULL,
    `ip_address` VARCHAR(45) DEFAULT NULL,
    `user_agent` VARCHAR(255) DEFAULT NULL,
    `session_id` VARCHAR(128) DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_ip` (`ip_address`),
    INDEX `idx_session` (`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ================================================================
-- 3. CATEGORIES TABLE
-- Normalized frame categories with sorting and status
-- ================================================================
CREATE TABLE IF NOT EXISTS `categories` (
    `id`         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name`       VARCHAR(100) NOT NULL,
    `slug`       VARCHAR(100) NOT NULL UNIQUE,
    `icon`       VARCHAR(50) DEFAULT 'fa-folder',
    `description` TEXT DEFAULT NULL,
    `sort_order` INT NOT NULL DEFAULT 0,
    `is_active`  TINYINT(1) NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_sort` (`sort_order`),
    INDEX `idx_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed default categories
INSERT INTO `categories` (`name`, `slug`, `icon`, `sort_order`) VALUES
    ('Political',      'political',      'fa-landmark',       1),
    ('News',           'news',           'fa-newspaper',      2),
    ('Breaking News',  'breaking-news',  'fa-bolt',           3),
    ('Sports',         'sports',         'fa-futbol',         4),
    ('Business',       'business',       'fa-briefcase',      5),
    ('Festival',       'festival',       'fa-star',           6),
    ('Islamic',        'islamic',        'fa-mosque',         7),
    ('Campaign',       'campaign',       'fa-bullhorn',       8),
    ('Custom',         'custom',         'fa-palette',        9)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

-- ================================================================
-- 4. FRAMES TABLE
-- Frame templates with JSON configuration for all element positions
-- The template_json column stores the complete positioning data
-- generated by the visual Frame Designer
-- ================================================================
CREATE TABLE IF NOT EXISTS `frames` (
    `id`             INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `category_id`    INT UNSIGNED DEFAULT NULL,
    `name`           VARCHAR(255) NOT NULL,
    `overlay_image`  VARCHAR(500) NOT NULL COMMENT 'Relative path to the transparent PNG frame',
    `thumbnail`      VARCHAR(500) DEFAULT NULL COMMENT 'Auto-generated small thumbnail',
    `template_json`  JSON NOT NULL COMMENT 'Complete JSON template with positions for image, logo, headline, date, time',
    `canvas_width`   INT UNSIGNED NOT NULL DEFAULT 1080,
    `canvas_height`  INT UNSIGNED NOT NULL DEFAULT 1080,
    `is_featured`    TINYINT(1) NOT NULL DEFAULT 0,
    `download_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `is_active`      TINYINT(1) NOT NULL DEFAULT 1,
    `created_at`     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at`     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `fk_frames_category` FOREIGN KEY (`category_id`)
        REFERENCES `categories` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    INDEX `idx_category` (`category_id`),
    INDEX `idx_featured` (`is_featured`),
    INDEX `idx_active` (`is_active`),
    INDEX `idx_downloads` (`download_count` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ================================================================
-- 5. FRAME_TEMPLATES TABLE
-- Version history for frame template designs (audit trail)
-- ================================================================
CREATE TABLE IF NOT EXISTS `frame_templates` (
    `id`            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `frame_id`      INT UNSIGNED NOT NULL,
    `template_data` JSON NOT NULL COMMENT 'Snapshot of template_json at this version',
    `version`       INT UNSIGNED NOT NULL DEFAULT 1,
    `created_by`    INT UNSIGNED DEFAULT NULL,
    `created_at`    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT `fk_templates_frame` FOREIGN KEY (`frame_id`)
        REFERENCES `frames` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `fk_templates_admin` FOREIGN KEY (`created_by`)
        REFERENCES `admins` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    INDEX `idx_frame_version` (`frame_id`, `version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ================================================================
-- 6. GENERATED_IMAGES TABLE
-- Log of all images generated by users
-- ================================================================
CREATE TABLE IF NOT EXISTS `generated_images` (
    `id`           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `frame_id`     INT UNSIGNED DEFAULT NULL,
    `user_id`      INT UNSIGNED DEFAULT NULL,
    `headline`     TEXT DEFAULT NULL,
    `user_image`   VARCHAR(500) DEFAULT NULL COMMENT 'Path to original uploaded user image',
    `logo_image`   VARCHAR(500) DEFAULT NULL COMMENT 'Path to uploaded logo',
    `output_image` VARCHAR(500) NOT NULL COMMENT 'Path to final generated composite image',
    `format`       ENUM('png', 'jpg', 'hd_png') NOT NULL DEFAULT 'png',
    `file_size`    INT UNSIGNED DEFAULT NULL COMMENT 'Output file size in bytes',
    `ip_address`   VARCHAR(45) DEFAULT NULL,
    `created_at`   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT `fk_generated_frame` FOREIGN KEY (`frame_id`)
        REFERENCES `frames` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_generated_user` FOREIGN KEY (`user_id`)
        REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    INDEX `idx_frame` (`frame_id`),
    INDEX `idx_user` (`user_id`),
    INDEX `idx_created` (`created_at` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ================================================================
-- 7. SETTINGS TABLE
-- Key-value store for application configuration
-- ================================================================
CREATE TABLE IF NOT EXISTS `settings` (
    `id`            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `setting_key`   VARCHAR(100) NOT NULL UNIQUE,
    `setting_value` TEXT DEFAULT NULL,
    `setting_group` VARCHAR(50) NOT NULL DEFAULT 'general',
    `description`   VARCHAR(255) DEFAULT NULL,
    `created_at`    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at`    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_group` (`setting_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed default settings
INSERT INTO `settings` (`setting_key`, `setting_value`, `setting_group`, `description`) VALUES
    ('site_name',           'Image Frame Generator',    'general',    'Application display name'),
    ('site_description',    'Create Professional News & Political Frame Posters', 'general', 'SEO meta description'),
    ('canvas_width',        '1080',                     'canvas',     'Default canvas width in pixels'),
    ('canvas_height',       '1080',                     'canvas',     'Default canvas height in pixels'),
    ('max_upload_size',     '10',                       'upload',     'Maximum upload size in MB'),
    ('watermark_enabled',   '0',                        'watermark',  'Enable/disable watermark on output'),
    ('watermark_text',      'Image Frame Generator',    'watermark',  'Watermark text overlay'),
    ('watermark_opacity',   '30',                       'watermark',  'Watermark opacity (0-100)'),
    ('default_font',        'HindSiliguri',             'typography', 'Default font family for headlines'),
    ('default_font_size',   '36',                       'typography', 'Default headline font size'),
    ('default_font_color',  '#ffffff',                  'typography', 'Default headline font color'),
    ('qr_enabled',          '0',                        'qr',         'Enable QR code on generated images'),
    ('qr_content',          '',                         'qr',         'QR code content URL or text'),
    ('timezone',            'Asia/Dhaka',               'general',    'Server timezone for date/time stamp')
ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
